<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);SA1402;SA1512;SA1515</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nerdbank.Json.AspNetCoreMvcFormatter\Nerdbank.Json.AspNetCoreMvcFormatter.csproj" />
    <PackageReference Include="PolyType" />
  </ItemGroup>

</Project>
