<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace />
    <NoWarn>$(NoWarn);SA1601</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nerdbank.Json.AspNetCoreMvcFormatter\Nerdbank.Json.AspNetCoreMvcFormatter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PolyType" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" VersionOverride="8.0.*" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" VersionOverride="9.0.*" Condition="'$(TargetFramework)' == 'net9.0'" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" VersionOverride="10.0.*" Condition="'$(TargetFramework)' == 'net10.0'" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))">
    <PackageReference Include="xunit.v3.assert.aot" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))">
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

</Project>
